const data = [
  {
    asin: "1940026091",
    title: "Pandemic (The Extinction Files, Book 1)",
    img: "https://images-na.ssl-images-amazon.com/images/I/91xrEMcvmQL.jpg",
    price: 7.81,
    category: "scifi",
    condition: "new",
  },
  {
    asin: "0316438960",
    title: "The Last Wish: Introducing the Witcher",
    img: "https://images-na.ssl-images-amazon.com/images/I/51eHtkVLL5L.jpg",
    price: 9.59,
    category: "fantasy",
    condition: "collectible",
  },
  {
    asin: "0425264041",
    title: "Shards of Hope (Psy-Changeling Novel, A)",
    img: "https://images-na.ssl-images-amazon.com/images/I/91ku%2B0LppPL.jpg",
    price: 7.59,
    category: "scifi",
    condition: "new",
  },
  {
    asin: "1509854525",
    title: "The Charmed Life of Alex Moore",
    img: "https://images-na.ssl-images-amazon.com/images/I/61PVMb6YCaL.jpg",
    price: 23.33,
    category: "scifi",
    condition: "used",
  },
  {
    asin: "0062059882",
    title: "American Gods: The Tenth Anniversary Edition: A Novel",
    img: "https://images-na.ssl-images-amazon.com/images/I/519mwdpzlmL.jpg",
    price: 14.94,
    category: "fantasy",
    condition: "new",
  },
  {
    asin: "0008120692",
    title: "The Ark (The Ark Trilogy, Book 1)",
    img: "https://images-na.ssl-images-amazon.com/images/I/51A8BmESq5L.jpg",
    price: 9.36,
    category: "scifi",
    condition: "used",
  },
  {
    asin: "1621579832",
    title:
      "Justice on Trial: The Kavanaugh Confirmation and the Future of the Supreme Court",
    img: "https://images-na.ssl-images-amazon.com/images/I/71WdFQNYSJL.jpg",
    price: 17.39,
    category: "history",
    condition: "collectible",
  },
  {
    asin: "1626493014",
    title: "Fall and Rising",
    img: "https://images-na.ssl-images-amazon.com/images/I/51e7A-DT9fL.jpg",
    price: 7.77,
    category: "scifi",
    condition: "new",
  },
  {
    asin: "0385349947",
    title: "Lean In: Women, Work, and the Will to Lead",
    img: "https://images-na.ssl-images-amazon.com/images/I/81coZ37EmxL.jpg",
    price: 14.3,
    category: "history",
    condition: "used",
  },
  {
    asin: "0743270754",
    title: "Team of Rivals: The Political Genius of Abraham Lincoln",
    img: "https://images-na.ssl-images-amazon.com/images/I/51bpOR8qigL.jpg",
    price: 13.14,
    category: "history",
    condition: "new",
  },
  {
    asin: "1623808928",
    title: "Children of Forever",
    img: "https://images-na.ssl-images-amazon.com/images/I/61hJ8Nc-KpL.jpg",
    price: 3.25,
    category: "scifi",
    condition: "collectible",
  },
  {
    asin: "0008288798",
    title: "A Reaper at the Gates (Ember Quartet, Book 3)",
    img: "https://images-na.ssl-images-amazon.com/images/I/91vFU0KCm9L.jpg",
    price: 12.6,
    category: "romance",
    condition: "used",
  },
  {
    asin: "0553808044",
    title:
      "A Game of Thrones: The Illustrated Edition: A Song of Ice and Fire: Book One",
    img: "https://images-na.ssl-images-amazon.com/images/I/A12tbaSby%2BL.jpg",
    price: 28.06,
    category: "fantasy",
    condition: "new",
  },
  {
    asin: "1578562953",
    title: "Edge of Eternity",
    img: "https://images-na.ssl-images-amazon.com/images/I/91Ft%2BN5q0sL.jpg",
    price: 15.19,
    category: "romance",
    condition: "new",
  },
  {
    asin: "1629143715",
    title: "The Man from Battle Flat: A Western Trio",
    img: "https://images-na.ssl-images-amazon.com/images/I/71GCjmvwIjL.jpg",
    price: 11.91,
    category: "romance",
    condition: "new",
  },
  {
    asin: "156975599X",
    title: "Patriots: A Novel of Survival in the Coming Collapse",
    img: "https://images-na.ssl-images-amazon.com/images/I/51REczj2RJL.jpg",
    price: 14.0,
    category: "horror",
    condition: "new",
  },
  {
    asin: "0735215251",
    title: "The Pharaoh's Secret (The NUMA Files)",
    img: "https://images-na.ssl-images-amazon.com/images/I/71EOFkXiVxL.jpg",
    price: 6.79,
    category: "horror",
    condition: "new",
  },
  {
    asin: "0399177574",
    title: "Illidan: World of Warcraft: A Novel",
    img: "https://images-na.ssl-images-amazon.com/images/I/81khLUoMKaL.jpg",
    price: 6.12,
    category: "horror",
    condition: "used",
  },
];
